/**
 * Attire Directory data.
 * Transcribed from "Directory and Details.xlsx" (research compiled from public
 * sources, not direct outreach — see Legend & Notes tab in that file).
 * verified:true corresponds to the sheet's "Verified" status; everything else
 * is "Unverified — pending outreach" and must not be presented as confirmed.
 * Fields left out of the sheet ("To verify": phone, email, contact, certain
 * addresses, certificates, years, MOQ) are intentionally omitted here rather
 * than guessed.
 */

var CATEGORIES = [
  {
    id: "materials",
    label: "Materials & Making",
    color: "sage",
    blurb: "Fabric sourcing, manufacturing & cut-and-sew, deadstock & resale marketplaces",
  },
  {
    id: "circularity",
    label: "Circularity & Disposal",
    color: "terracotta",
    blurb: "Textile recycling, waste diversion & disposal",
  },
  {
    id: "strategy",
    label: "Strategy & Expertise",
    color: "slate",
    blurb: "Supply chain consultants & production technology",
  },
  {
    id: "advocacy",
    label: "Advocacy & Community",
    color: "gold",
    blurb: "NGOs, nonprofits & public institutions",
  },
  {
    id: "retail",
    label: "Retail & Creators",
    color: "plum",
    blurb: "Slow fashion designers, stores & secondhand marketplaces",
  },
];

var BOROUGHS = ["Manhattan", "Brooklyn", "Queens", "Staten Island", "Bronx", "NYC Presence"];

var LISTINGS = [
  {
    id: "fabscrap",
    name: "FabScrap",
    category: "circularity",
    subcategory: "Disposal & Recycling",
    borough: "Brooklyn",
    verified: true,
    tag: "Nonprofit 501(c)(3)",
    description:
      "Nonprofit textile recycling and resale; collects pre- and post-consumer fabric waste from fashion and design brands and diverts it from landfill via resale, reuse, and recycling.",
    goodToKnow: "Reports 800+ brand partners and publishes public landfill-diversion data.",
  },
  {
    id: "helpsy",
    name: "Helpsy",
    category: "circularity",
    subcategory: "Disposal & Recycling",
    borough: "NYC Presence",
    verified: false,
    tag: "Certified B Corporation",
    description:
      "Clothing and textile collection company running donation bins across NYC in partnership with the NYC Department of Sanitation and NYSID; resells or recycles roughly 95% of what it collects rather than sending it to landfill.",
    goodToKnow: "Company facility is based in White Plains, NY, just outside the five boroughs, with roughly 700 of its ~2,000 collection bins placed within NYC itself.",
  },
  {
    id: "queen-of-raw",
    name: "Queen of Raw",
    category: "materials",
    subcategory: "Deadstock & Resale Marketplaces",
    borough: "NYC Presence",
    verified: false,
    description:
      "Online marketplace for buying and selling deadstock and excess fabric inventory; also offers Materia, an impact-measurement tool for brands.",
    goodToKnow: "Operates as much as a platform/peer as a directory listing.",
  },
  {
    id: "natasha-fabric",
    name: "Natasha Fabric",
    category: "materials",
    subcategory: "Fabric Sourcing & Sustainable Textiles",
    borough: "NYC Presence",
    verified: false,
    description:
      "Sustainable fabric wholesaler offering organic cotton, hemp, Tencel, and recycled polyester.",
  },
  {
    id: "sourcing-district",
    name: "The Sourcing District",
    category: "materials",
    subcategory: "Fabric Sourcing & Sustainable Textiles",
    borough: "NYC Presence",
    verified: false,
    description: "NYC-based rep group representing sustainable and performance fabric mills to brands.",
    goodToKnow: "Represents multiple mills; not all mill locations are NYC-based.",
  },
  {
    id: "loom-and-stars",
    name: "Loom & Stars",
    category: "materials",
    subcategory: "Fabric Sourcing & Sustainable Textiles",
    borough: "NYC Presence",
    verified: false,
    description: "Handmade, natural-fiber fabric supplier with a by-appointment NYC showroom.",
    goodToKnow: "By-appointment only.",
  },
  {
    id: "fabscrap-retail",
    name: "FabScrap Retail / Wholesale Shop",
    category: "materials",
    subcategory: "Deadstock & Resale Marketplaces",
    borough: "Brooklyn",
    verified: true,
    tag: "Nonprofit-affiliated",
    description: "Retail and wholesale arm of FabScrap selling reclaimed deadstock fabric.",
    goodToKnow: "Operates under the FabScrap 501(c)(3).",
  },
  {
    id: "mood-fabrics",
    name: "Mood Fabrics",
    category: "materials",
    subcategory: "Fabric Sourcing & Sustainable Textiles",
    borough: "Manhattan",
    verified: false,
    description: "Long-standing Garment District fabric retailer; carries some deadstock and natural-fiber lines.",
  },
  {
    id: "bj-fabrics",
    name: "B&J Fabrics",
    category: "materials",
    subcategory: "Fabric Sourcing & Sustainable Textiles",
    borough: "Manhattan",
    verified: false,
    description: "Long-standing Garment District wholesale fabric source; some natural-fiber and deadstock options.",
  },
  {
    id: "spandex-house",
    name: "Spandex House",
    category: "materials",
    subcategory: "Fabric Sourcing & Sustainable Textiles",
    borough: "Manhattan",
    verified: false,
    description: "Garment District fabric retailer; offers some recycled and performance fabric options.",
  },
  {
    id: "carina",
    name: "Carina",
    category: "materials",
    subcategory: "Manufacturing & Cut-and-Sew",
    borough: "Manhattan",
    verified: false,
    yearsNote: "Est. 1996 (self-reported)",
    description: "Leather and shearling manufacturing specialist; sources sustainable and repurposed materials.",
  },
  {
    id: "apparel-production-inc",
    name: "Apparel Production Inc.",
    category: "materials",
    subcategory: "Manufacturing & Cut-and-Sew",
    borough: "Manhattan",
    verified: false,
    description: "Full design-to-production manufacturing services.",
  },
  {
    id: "grace-apparel",
    name: "Grace Apparel Production",
    category: "materials",
    subcategory: "Manufacturing & Cut-and-Sew",
    borough: "Manhattan",
    verified: false,
    description: "Full in-house apparel manufacturing capability.",
  },
  {
    id: "the-factory-nyc",
    name: "The Factory NYC",
    category: "materials",
    subcategory: "Manufacturing & Cut-and-Sew",
    borough: "Brooklyn",
    verified: false,
    description: "Brooklyn-based small-batch apparel manufacturer.",
  },
  {
    id: "minimalist",
    name: "Minimalist",
    category: "materials",
    subcategory: "Manufacturing & Cut-and-Sew",
    borough: "Manhattan",
    verified: false,
    description: "Garment District manufacturer with a stated sustainability and ethical-manufacturing focus.",
  },
  {
    id: "nyc-sewn",
    name: "NYC Sewn",
    category: "materials",
    subcategory: "Manufacturing & Cut-and-Sew",
    borough: "NYC Presence",
    verified: false,
    description: "Small-batch manufacturer geared toward independent designers.",
  },
  {
    id: "create-a-marker",
    name: "Create-A-Marker",
    category: "materials",
    subcategory: "Manufacturing & Cut-and-Sew",
    borough: "NYC Presence",
    verified: false,
    description: "Small-batch, made-to-order manufacturer; pattern-making and grading specialist.",
  },
  {
    id: "wing-and-weft",
    name: "Wing & Weft Gloves",
    category: "materials",
    subcategory: "Manufacturing & Cut-and-Sew",
    borough: "Manhattan",
    verified: false,
    description: "Heritage glove atelier; small-batch production.",
  },
  {
    id: "stylus-apparel",
    name: "Stylus Apparel",
    category: "materials",
    subcategory: "Manufacturing & Cut-and-Sew",
    borough: "Outer Boroughs",
    verified: false,
    description: "Factory-direct manufacturer positioned as startup-friendly.",
  },
  {
    id: "stateless",
    name: "Stateless",
    category: "strategy",
    subcategory: "Supply Chain Consultants",
    borough: "NYC Presence",
    verified: false,
    description: "Fashion consulting firm covering supply chain strategy and production management.",
  },
  {
    id: "stellar-fashion-consulting",
    name: "Stellar Fashion Consulting",
    category: "strategy",
    subcategory: "Supply Chain Consultants",
    borough: "Manhattan",
    verified: false,
    yearsNote: "~20 years (self-reported)",
    description: "Production and PLM (product lifecycle management) consulting firm.",
  },
  {
    id: "suuchi",
    name: "Suuchi Inc.",
    category: "strategy",
    subcategory: "Supply Chain & Logistics Technology",
    borough: "NYC Presence",
    verified: false,
    description: "Supply chain technology company offering a digital production management platform.",
  },
  {
    id: "glass-factory",
    name: "Glass Factory",
    category: "strategy",
    subcategory: "Supply Chain & Logistics Technology",
    borough: "NYC Presence",
    verified: false,
    description:
      "Global factory-sourcing platform connecting fashion brands with vetted manufacturers; lists 100+ factories with photos, videos, MOQs, and production timelines.",
    goodToKnow: "Operates as a global, largely remote platform (factories documented across Japan, Italy, Portugal, China, and elsewhere) — no confirmed physical NYC office found.",
  },
  {
    id: "nycftc",
    name: "NYC Fair Trade Coalition (NYCFTC)",
    category: "advocacy",
    subcategory: "NGOs & Nonprofits",
    borough: "NYC Presence",
    verified: true,
    description:
      "Coalition promoting fair trade principles, responsible business practice, and ethical supply chains; runs knowledge-exchange programming for NYC fashion stakeholders.",
    goodToKnow: "Documented partnerships with NYC Dept. of Sanitation and FabScrap.",
  },
  {
    id: "sfcc",
    name: "Sustainable Fashion Community Center (SFCC)",
    category: "advocacy",
    subcategory: "NGOs & Nonprofits",
    borough: "Manhattan",
    verified: true,
    description:
      "Community nonprofit focused on the 5 Rs (reduce, reuse, recycle, repurpose, repair); runs The Swap Shop and textile collection programs.",
    goodToKnow: "Publicly tracks and shares pounds diverted via its own Impact Form.",
  },
  {
    id: "cfda",
    name: "CFDA (Council of Fashion Designers of America)",
    category: "advocacy",
    subcategory: "NGOs & Nonprofits",
    borough: "NYC Presence",
    verified: true,
    tag: "National trade body",
    description:
      "National trade association running a Sustainability/IMPACT program and a materials-sourcing vendor directory; partners with NYCEDC on manufacturing funding initiatives.",
  },
  {
    id: "nycedc-fmi",
    name: "NYCEDC Fashion Manufacturing Initiative / Local Production Fund",
    category: "advocacy",
    subcategory: "NGOs & Nonprofits",
    borough: "NYC Presence",
    verified: true,
    tag: "City government program",
    description: "Public-private initiative connecting NYC manufacturers with brands; administers a $1.7M Local Production Fund.",
  },
  {
    id: "fit",
    name: "FIT (Fashion Institute of Technology)",
    category: "advocacy",
    subcategory: "NGOs & Nonprofits",
    borough: "Manhattan",
    verified: true,
    tag: "Public institution",
    description: "Public college hosting the Sustainable Business and Design Conference and broader industry convening programs.",
  },
  {
    id: "nyu-ffg",
    name: "NYU Future Fashion Group / Future Fashion Frontier",
    category: "advocacy",
    subcategory: "NGOs & Nonprofits",
    borough: "Manhattan",
    verified: false,
    tag: "Student organization",
    description: "NYU student sustainability club running swap shops and mending workshops.",
  },
  {
    id: "malaika-ny",
    name: "Malaika NY",
    category: "retail",
    subcategory: "Sustainable Apparel Brand",
    borough: "NYC Presence",
    verified: false,
    description: "Zero-waste womenswear label using pattern-cutting techniques that eliminate fabric offcuts; produced locally in New York City.",
  },
  {
    id: "337-brand",
    name: "337 Brand",
    category: "retail",
    subcategory: "Sustainable Apparel Brand",
    borough: "NYC Presence",
    verified: false,
    description: "Sustainable leisurewear line made from earth-friendly materials, produced locally in Brooklyn and Queens.",
  },
  {
    id: "conscious-step",
    name: "Conscious Step",
    category: "retail",
    subcategory: "Sustainable Apparel Brand",
    borough: "Brooklyn",
    verified: false,
    description: "Organic, Fairtrade, and vegan socks, sweatshirts, and accessories; each design supports a specific charitable cause.",
  },
  {
    id: "another-tomorrow",
    name: "Another Tomorrow",
    category: "retail",
    subcategory: "Sustainable Apparel Brand",
    borough: "Manhattan",
    verified: false,
    description: "Traceable, sustainably made womenswear brand founded by Vanessa Barboni Hallik, with supply chain details published for each garment.",
  },
  {
    id: "zero-waste-daniel",
    name: "Zero Waste Daniel",
    category: "retail",
    subcategory: "Sustainable Apparel Brand",
    borough: "Brooklyn",
    verified: false,
    description: "Bushwick studio and shop making clothing entirely from pre- and post-consumer textile scraps; a well-known pioneer of zero-waste design.",
  },
  {
    id: "rentrayage",
    name: "Rentrayage",
    category: "retail",
    subcategory: "Sustainable Apparel Brand",
    borough: "Manhattan",
    verified: false,
    description: "Handcrafted, one-of-a-kind and limited-edition pieces made from recycled and vintage materials, founded by designer Erin Beatty.",
  },
  {
    id: "monique-pean",
    name: "Monique Péan",
    category: "retail",
    subcategory: "Sustainable Jewelry",
    borough: "Manhattan",
    verified: false,
    description: "Fine jewelry designer working exclusively with sustainably and fair-trade sourced materials; each piece handcrafted from a SoHo studio.",
  },
  {
    id: "araks",
    name: "Araks",
    category: "retail",
    subcategory: "Sustainable Apparel Brand",
    borough: "Manhattan",
    verified: false,
    description: "Designer lingerie and ready-to-wear label known for size-inclusive fits and small-batch, ethically made production.",
  },
  {
    id: "hyer-goods",
    name: "Hyer Goods",
    category: "retail",
    subcategory: "Sustainable Footwear & Accessories",
    borough: "Brooklyn",
    verified: false,
    description: "Handbags and wallets made from luxury deadstock leather and plastic-free eco alternatives.",
  },
  {
    id: "futura-jewelry",
    name: "Futura Jewelry",
    category: "retail",
    subcategory: "Sustainable Jewelry",
    borough: "Manhattan",
    verified: false,
    description: "Fine jewelry made exclusively from Fairmined Ecological gold, sourced to eliminate mercury and cyanide use in mining; crafted in an NYC workshop.",
  },
  {
    id: "article22",
    name: "Article22",
    category: "retail",
    subcategory: "Sustainable Jewelry",
    borough: "Brooklyn",
    verified: false,
    description: "Jewelry handmade by artisans in Laos from recycled war-era scrap metal, including unexploded ordnance casings; brand co-founded and based in Greenpoint.",
  },
  {
    id: "behno",
    name: "Behno",
    category: "retail",
    subcategory: "Sustainable Footwear & Accessories",
    borough: "NYC Presence",
    verified: false,
    description: "Leather handbags designed in New York and ethically manufactured in India using LWG-certified, low-impact tanneries.",
  },
  {
    id: "kordal-studio",
    name: "Kordal Studio",
    category: "retail",
    subcategory: "Sustainable Apparel Brand",
    borough: "Brooklyn",
    verified: false,
    description: "Crown Heights label making responsibly produced knitwear and ready-to-wear from natural and organic textiles.",
  },
  {
    id: "study-ny",
    name: "Study NY",
    category: "retail",
    subcategory: "Sustainable Apparel Brand",
    borough: "Manhattan",
    verified: false,
    description: "Lower East Side womenswear label known for versatile, minimalist silhouettes made with sustainable fabrics.",
  },
  {
    id: "warp-and-weft",
    name: "Warp + Weft",
    category: "retail",
    subcategory: "Sustainable Apparel Brand",
    borough: "Manhattan",
    verified: false,
    description: "Size-inclusive denim brand focused on water-saving washes and responsible manufacturing.",
  },
  {
    id: "arielle-ratner",
    name: "Arielle Ratner",
    category: "retail",
    subcategory: "Sustainable Jewelry",
    borough: "NYC Presence",
    verified: false,
    description: "Semi-bespoke and bespoke fine jewelry designer specializing in antique diamonds, handmade in New York.",
  },
  {
    id: "gunas",
    name: "Gunas New York",
    category: "retail",
    subcategory: "Sustainable Footwear & Accessories",
    borough: "Queens",
    verified: false,
    description: "Luxury vegan handbag brand founded in 2009, based in Long Island City.",
  },
  {
    id: "veerah",
    name: "Veerah",
    category: "retail",
    subcategory: "Sustainable Footwear & Accessories",
    borough: "Manhattan",
    verified: false,
    description: "Women-led designer vegan shoe brand built to prove cruelty-free footwear can be high-fashion.",
  },
  {
    id: "the-cotton-bride",
    name: "The Cotton Bride",
    category: "retail",
    subcategory: "Sustainable Apparel Brand",
    borough: "Queens",
    verified: false,
    description: "Couture bridal and evening-wear studio making one-of-a-kind gowns by hand from 100% natural fabrics, based in Long Island City.",
  },
  {
    id: "voz",
    name: "Voz",
    category: "retail",
    subcategory: "Sustainable Apparel Brand",
    borough: "Manhattan",
    verified: false,
    description: "Artisanal luxury fashion brand collaborating directly with Indigenous weavers on handmade textiles.",
  },
  {
    id: "seek-collective",
    name: "Seek Collective",
    category: "retail",
    subcategory: "Sustainable Apparel Brand",
    borough: "Brooklyn",
    verified: false,
    description: "Elevated essentials made through partnerships with artisan communities in India, using hand block-printing, natural dyeing, and handloom weaving.",
  },
  {
    id: "dl1961",
    name: "DL1961",
    category: "retail",
    subcategory: "Sustainable Apparel Brand",
    borough: "Manhattan",
    verified: false,
    description: "Premium denim brand known for water-saving dyeing and finishing processes, headquartered in the Garment District.",
  },
  {
    id: "emilia-george",
    name: "Emilia George",
    category: "retail",
    subcategory: "Sustainable Apparel Brand",
    borough: "Manhattan",
    verified: false,
    description: "Maternity and nursing wear made from OEKO-TEX-certified, largely vegan and recycled fabrics; designed and manufactured in Manhattan.",
  },
  {
    id: "misha-nonoo",
    name: "Misha Nonoo",
    category: "retail",
    subcategory: "Sustainable Apparel Brand",
    borough: "Manhattan",
    verified: false,
    description: "Ready-to-wear label known for its signature convertible, versatile-fit designs.",
  },
  {
    id: "gabriela-hearst",
    name: "Gabriela Hearst",
    category: "retail",
    subcategory: "Sustainable Apparel Brand",
    borough: "Manhattan",
    verified: false,
    description: "Luxury ready-to-wear house built around sustainable materials, ethical production, and reduced-waste practices.",
  },
  {
    id: "zero-maria-cornejo",
    name: "Zero + Maria Cornejo",
    category: "retail",
    subcategory: "Sustainable Apparel Brand",
    borough: "Manhattan",
    verified: false,
    description: "Longtime NYC ready-to-wear label known for sculptural, sustainably minded design.",
  },
  {
    id: "urban-zen",
    name: "Urban Zen",
    category: "retail",
    subcategory: "Sustainable Apparel Brand",
    borough: "Manhattan",
    verified: false,
    description: "Donna Karan's lifestyle brand combining fashion, wellness, and philanthropy, anchored by a West Village flagship.",
  },
  {
    id: "nicholas-k",
    name: "Nicholas K",
    category: "retail",
    subcategory: "Sustainable Apparel Brand",
    borough: "NYC Presence",
    verified: false,
    description: "Sister-designed ready-to-wear label known for organic and natural-fiber fabrics.",
  },
  {
    id: "ulla-johnson",
    name: "Ulla Johnson",
    category: "retail",
    subcategory: "Sustainable Apparel Brand",
    borough: "Manhattan",
    verified: false,
    description: "Contemporary ready-to-wear label known for artisanal detailing and small-batch production techniques.",
  },
  {
    id: "bhoomki",
    name: "Bhoomki",
    category: "retail",
    subcategory: "Sustainable Apparel Brand",
    borough: "Brooklyn",
    verified: false,
    description: "Park Slope boutique and label curating and designing size-inclusive, sustainably made clothing.",
  },
  {
    id: "madewell",
    name: "Madewell",
    category: "retail",
    subcategory: "Sustainable Apparel Brand",
    borough: "Manhattan",
    verified: false,
    description: "National apparel retailer (J.Crew Group) headquartered in Lower Manhattan, with a denim recycling program and responsibly sourced material lines.",
  },
  {
    id: "brother-vellies",
    name: "Brother Vellies",
    category: "retail",
    subcategory: "Sustainable Footwear & Accessories",
    borough: "Brooklyn",
    verified: false,
    description: "Footwear and accessories brand founded by Aurora James, working with traditional artisan techniques across Africa to preserve handcraft manufacturing jobs.",
  },
  {
    id: "artists-and-fleas",
    name: "Artists & Fleas",
    category: "retail",
    subcategory: "Independent Marketplace",
    borough: "NYC Presence",
    verified: false,
    description: "Curated market platform for independent designers, vintage sellers, and artists across multiple NYC locations.",
  },
  {
    id: "illesteva",
    name: "Illesteva",
    category: "retail",
    subcategory: "Sustainable Footwear & Accessories",
    borough: "NYC Presence",
    verified: false,
    description: "New York-founded eyewear brand with recycled and bio-based acetate frame lines.",
  },
  {
    id: "wgaca",
    name: "What Goes Around Comes Around",
    category: "retail",
    subcategory: "Secondhand & Vintage Resale",
    borough: "Manhattan",
    verified: false,
    description: "SoHo-founded luxury vintage and resale retailer specializing in authenticated archival pieces from major fashion houses.",
  },
  {
    id: "beacons-closet",
    name: "Beacon's Closet",
    category: "retail",
    subcategory: "Secondhand & Vintage Resale",
    borough: "Brooklyn",
    verified: false,
    description: "Long-running Brooklyn secondhand clothing chain buying and reselling used and vintage apparel.",
  },
  {
    id: "rachel-comey",
    name: "Rachel Comey",
    category: "retail",
    subcategory: "Sustainable Apparel Brand",
    borough: "Manhattan",
    verified: false,
    description: "Tribeca-based ready-to-wear and footwear label known for domestic, small-batch manufacturing.",
  },
  {
    id: "narativ-house",
    name: "The Narativ House",
    category: "retail",
    subcategory: "Independent Marketplace",
    borough: "Brooklyn",
    verified: false,
    description: "Bed-Stuy concept store and social-good venture spotlighting ethically sourced artisan brands from around the world.",
  },
  {
    id: "only-hearts",
    name: "Only Hearts",
    category: "retail",
    subcategory: "Sustainable Apparel Brand",
    borough: "Manhattan",
    verified: false,
    description: "Family-run lingerie and intimates label manufacturing in New York City since 1978.",
  },
  {
    id: "pamela-love",
    name: "Pamela Love",
    category: "retail",
    subcategory: "Sustainable Jewelry",
    borough: "NYC Presence",
    verified: false,
    description: "New York jewelry designer known for handcrafted, nature-inspired fine jewelry.",
  },
  {
    id: "catbird",
    name: "Catbird",
    category: "retail",
    subcategory: "Sustainable Jewelry",
    borough: "Brooklyn",
    verified: false,
    description: "Williamsburg jewelry brand known for delicate, ethically sourced fine jewelry with in-house recycled-gold casting.",
  },
  {
    id: "mociun",
    name: "Mociun",
    category: "retail",
    subcategory: "Sustainable Jewelry",
    borough: "Brooklyn",
    verified: false,
    description: "Williamsburg fine jewelry and home goods brand using rare and unusual stones, handmade in New York.",
  },
  {
    id: "nanushka",
    name: "Nanushka",
    category: "retail",
    subcategory: "Sustainable Apparel Brand",
    borough: "Manhattan",
    verified: false,
    description: "Ready-to-wear label with a SoHo flagship store and café.",
    goodToKnow: "Headquartered in Budapest; NYC presence is retail only.",
  },
  {
    id: "bario-neal",
    name: "Bario Neal",
    category: "retail",
    subcategory: "Sustainable Jewelry",
    borough: "Brooklyn",
    verified: false,
    description: "Ethically sourced fine jewelry brand with a Brooklyn showroom.",
    goodToKnow: "Headquartered and produced in Philadelphia; Brooklyn location is a showroom only.",
  },
  {
    id: "eileen-fisher",
    name: "Eileen Fisher",
    category: "retail",
    subcategory: "Sustainable Apparel Brand",
    borough: "Manhattan",
    verified: false,
    description: "Women's clothing brand with a Manhattan design studio and numerous NYC retail stores; known for its Renew take-back and resale program.",
    goodToKnow: "Corporate HQ is in Irvington, NY, just north of the city line.",
  },
  {
    id: "the-realreal",
    name: "The RealReal",
    category: "retail",
    subcategory: "Secondhand & Vintage Resale",
    borough: "Manhattan",
    verified: false,
    description: "Online and in-store luxury resale platform with an office and consignment/retail locations in Manhattan.",
    goodToKnow: "Corporate HQ is in San Francisco.",
  },
  {
    id: "miakoda",
    name: "Miakoda",
    category: "retail",
    subcategory: "Sustainable Apparel Brand",
    borough: "NYC Presence",
    verified: false,
    description: "Slow-fashion womenswear label ethically manufactured in local New York City factories.",
    goodToKnow: "Mailing address is in New Hyde Park, NY (Nassau County), just outside the five boroughs.",
  },
  {
    id: "day-won",
    name: "Day/Won",
    category: "retail",
    subcategory: "Sustainable Apparel Brand",
    borough: "NYC Presence",
    verified: false,
    description: "Fully size-inclusive activewear brand (sizes 0–32) founded by model Candice Huffine.",
    goodToKnow: "Manufactures on-demand upstate; founder is New York-based.",
  },
  {
    id: "jade-swim",
    name: "JADE Swim",
    category: "retail",
    subcategory: "Sustainable Apparel Brand",
    borough: "NYC Presence",
    verified: false,
    description: "Swimwear label founded in New York City.",
    goodToKnow: "Design and manufacturing are now based in Los Angeles.",
  },
  {
    id: "melissa-joy-manning",
    name: "Melissa Joy Manning",
    category: "retail",
    subcategory: "Sustainable Jewelry",
    borough: "Brooklyn",
    verified: false,
    description: "Fine jewelry designer with a namesake store in Brooklyn.",
    goodToKnow: "Design studio and primary production is in Berkeley, CA; the Brooklyn location is retail only.",
  },
  {
    id: "threads-4-thought",
    name: "Threads 4 Thought",
    category: "retail",
    subcategory: "Sustainable Apparel Brand",
    borough: "Manhattan",
    verified: false,
    description: "Sustainable basics brand with a business office in the Garment District.",
    goodToKnow: "Headquartered in Los Angeles; sold mainly through wholesale and department stores rather than a brand-owned NYC storefront.",
  },
  {
    id: "bhava",
    name: "Bhava",
    category: "retail",
    subcategory: "Sustainable Footwear & Accessories",
    borough: "Brooklyn",
    verified: false,
    description: "Vegan footwear brand with an East Williamsburg showroom, open by appointment.",
    goodToKnow: "Products are crafted in Spain; brand was NY-founded.",
  },
  {
    id: "chelsea-bravo",
    name: "Chelsea Bravo",
    category: "retail",
    subcategory: "Sustainable Apparel Brand",
    borough: "Brooklyn",
    verified: false,
    description: "Unisex, sustainably minded fashion label designed from a Brooklyn studio.",
  },
  {
    id: "reformation",
    name: "Reformation",
    category: "retail",
    subcategory: "Sustainable Apparel Brand",
    borough: "Manhattan",
    verified: false,
    description: "Sustainable fashion retailer with multiple NYC stores.",
    goodToKnow: "Headquartered in Los Angeles.",
  },
  {
    id: "levis",
    name: "Levi's",
    category: "retail",
    subcategory: "Sustainable Apparel Brand",
    borough: "Manhattan",
    verified: false,
    description: "Denim brand running a SecondHand resale program, with multiple NYC retail stores.",
    goodToKnow: "Headquartered in San Francisco.",
  },
  {
    id: "allbirds",
    name: "Allbirds",
    category: "retail",
    subcategory: "Sustainable Footwear & Accessories",
    borough: "Manhattan",
    verified: false,
    description: "Sustainable footwear brand with NYC retail stores.",
    goodToKnow: "Headquartered in San Francisco.",
  },
  {
    id: "veja",
    name: "Veja",
    category: "retail",
    subcategory: "Sustainable Footwear & Accessories",
    borough: "NYC Presence",
    verified: false,
    description: "Sustainable sneaker brand with stores in Nolita and Williamsburg, including an in-house repair cobbler.",
    goodToKnow: "Headquartered in France.",
  },
  {
    id: "rothys",
    name: "Rothy's",
    category: "retail",
    subcategory: "Sustainable Footwear & Accessories",
    borough: "Manhattan",
    verified: false,
    description: "Footwear brand made from recycled plastic, with NYC retail stores.",
    goodToKnow: "Headquartered in San Francisco.",
  },
  {
    id: "cuyana",
    name: "Cuyana",
    category: "retail",
    subcategory: "Sustainable Apparel Brand",
    borough: "Manhattan",
    verified: false,
    description: "\"Fewer, better\" accessories and apparel brand with two NYC stores (SoHo and Madison Avenue).",
    goodToKnow: "Headquartered in Los Angeles.",
  },
  {
    id: "everlane",
    name: "Everlane",
    category: "retail",
    subcategory: "Sustainable Apparel Brand",
    borough: "NYC Presence",
    verified: false,
    description: "Transparent-pricing apparel brand with stores in SoHo and Williamsburg.",
    goodToKnow: "Headquartered in San Francisco.",
  },
  {
    id: "fjallraven",
    name: "Fjällräven",
    category: "retail",
    subcategory: "Sustainable Apparel Brand",
    borough: "NYC Presence",
    verified: false,
    description: "Outdoor apparel brand with three NYC stores (SoHo, Nolita, and the Meatpacking District).",
    goodToKnow: "Headquartered in Sweden.",
  },
  {
    id: "nudie-jeans",
    name: "Nudie Jeans",
    category: "retail",
    subcategory: "Sustainable Apparel Brand",
    borough: "Manhattan",
    verified: false,
    description: "Organic denim brand with a Bowery repair shop offering free lifetime denim repair.",
    goodToKnow: "Headquartered in Sweden.",
  },
  {
    id: "atelier-jolie",
    name: "Atelier Jolie",
    category: "advocacy",
    subcategory: "Community & Cultural Space",
    borough: "Manhattan",
    verified: false,
    description: "Angelina Jolie's NoHo atelier hosting classes, workshops, artist residencies, and exhibitions spotlighting art, craft, and design from cultures around the world; also home to an in-house sustainable fashion collection and tailoring collective.",
    goodToKnow: "Located at 57 Great Jones St, the former Basquiat/Warhol studio.",
  },
  {
    id: "spinnova",
    name: "Spinnova",
    category: "circularity",
    subcategory: "Circular Materials Innovation",
    borough: "NYC Presence",
    verified: false,
    description: "Finnish textile innovator turning wood-based cellulose into a wool-like fiber that stretches like cotton, with no process waste besides water evaporation.",
    goodToKnow: "Engages the NYC market through New York Fashion Week runway collaborations (Ka Wa Key, Flying Solo) and Kingpins NY trade show showcases; headquartered in Finland.",
  },
  {
    id: "mother-of-pearl",
    name: "Mother of Pearl",
    category: "retail",
    subcategory: "Sustainable Apparel Brand",
    borough: "Manhattan",
    verified: false,
    description: "London luxury sustainable womenswear label founded by Maia Norman, exported worldwide and stocked by premium U.S. retailers including Saks Fifth Avenue in NYC.",
    goodToKnow: "Headquartered in London; NYC presence is through retail stockists rather than a brand-owned store.",
  },
  {
    id: "chloe",
    name: "Chloé",
    category: "retail",
    subcategory: "Sustainable Apparel Brand",
    borough: "Manhattan",
    verified: false,
    description: "French luxury ready-to-wear house and the first major European luxury brand to achieve B Corp certification for its sustainability and social-impact commitments; carried by major NYC retailers.",
    goodToKnow: "Headquartered in Paris.",
  },
  {
    id: "rubi-laboratories",
    name: "Rubi Laboratories",
    category: "circularity",
    subcategory: "Circular Materials Innovation",
    borough: "NYC Presence",
    verified: false,
    description: "Startup converting carbon emissions into carbon-negative cellulosic textiles using a proprietary biocatalytic 'symbiotic manufacturing' process, starting with viscose.",
    goodToKnow: "Co-founders Neeka and Leila Mashouf presented on stage at the BoF Professional Summit in Manhattan; runs a pilot/testing partnership with Reformation (which has NYC retail and corporate offices), alongside H&M, Ganni, Patagonia, and Nuuly. Headquartered in Alameda, CA.",
  },
  {
    id: "ganni",
    name: "Ganni",
    category: "retail",
    subcategory: "Sustainable Apparel Brand",
    borough: "Manhattan",
    verified: false,
    description: "Danish contemporary fashion brand with roughly half its fabric composition recycled, alongside responsible packaging, manufacturing, and materials commitments.",
    goodToKnow: "SoHo flagship at 40 Mercer St was its first U.S. store (2019); also has a Brooklyn location. Headquartered in Copenhagen.",
  },
  {
    id: "patagonia",
    name: "Patagonia",
    category: "retail",
    subcategory: "Sustainable Apparel Brand",
    borough: "Manhattan",
    verified: false,
    description: "Outdoor apparel brand sourcing roughly 87% recycled materials (recycled bottles, factory-floor pre-consumer scraps, recycled nylon and fishing nets) across its line.",
    goodToKnow: "SoHo flagship at 61-63 Crosby St includes a free repair station and community workspace. Headquartered in Ventura, CA.",
  },
  {
    id: "ellen-macarthur-foundation",
    name: "Ellen MacArthur Foundation",
    category: "advocacy",
    subcategory: "NGOs & Nonprofits",
    borough: "NYC Presence",
    verified: false,
    description: "Circular economy foundation that partnered with the City of New York as a Strategic Partner City, running the #WearNext campaign with ASOS, Gap, and H&M to reduce municipal clothing waste.",
    goodToKnow: "Opened a New York City location following this partnership; headquartered on the Isle of Wight, UK. Tapestry (Coach, Kate Spade) is also a Network partner.",
  },
  {
    id: "supercircle",
    name: "SuperCircle",
    category: "strategy",
    subcategory: "Supply Chain & Logistics Technology",
    borough: "NYC Presence",
    verified: false,
    description: "Tech and reverse-logistics platform bridging retail and textile waste; manages tech, shipping, and warehousing for brands' end-of-life apparel, footwear, and accessories.",
    goodToKnow: "Headquartered in New York; works with 150+ brand partners including J.Crew, GUESS, tentree, and Girlfriend Collective.",
  },
  {
    id: "mabel-industries",
    name: "Mabel Industries",
    category: "circularity",
    subcategory: "Circular Materials Innovation",
    borough: "NYC Presence",
    verified: false,
    description: "Producer of AppleSkin, a vegan leather alternative that replaces roughly half of fossil-fuel inputs with apple industry waste (peels and cores).",
    goodToKnow: "Material was used by NYC-based brand Mansur Gavriel in a bucket bag; headquartered in Florence, Italy.",
  },
  {
    id: "grace-ling",
    name: "Grace Ling",
    category: "retail",
    subcategory: "Sustainable Apparel Brand",
    borough: "Manhattan",
    verified: false,
    description: "Singapore-born, New York-based designer merging 3D-printed aero-aluminum hardware (infinitely recyclable) with zero-waste, computer-calculated garment construction.",
    goodToKnow: "Studied at Parsons School of Design in NYC; opened her first retail store in Manhattan between Hudson Yards and Times Square.",
  },
  {
    id: "kintra-fibers",
    name: "Kintra Fibers",
    category: "circularity",
    subcategory: "Circular Materials Innovation",
    borough: "Brooklyn",
    verified: false,
    description: "Biobased polyester innovator making a compostable, corn-derived alternative (roughly 56% corn-sourced) to conventional polyester.",
    goodToKnow: "Backed by H&M Group Ventures, with partnerships across global apparel brands.",
  },
  {
    id: "altana",
    name: "Altana",
    category: "strategy",
    subcategory: "Supply Chain & Logistics Technology",
    borough: "Brooklyn",
    verified: false,
    description: "AI-powered supply chain intelligence platform connecting data on products, shipments, and companies across global trade networks.",
    goodToKnow: "Raised $322M in funding; headquartered in Williamsburg, Brooklyn.",
  },
  {
    id: "sensoria",
    name: "Sensoria",
    category: "retail",
    subcategory: "Independent Marketplace",
    borough: "Manhattan",
    verified: false,
    description: "Curated e-commerce platform selling off-season and archival sample collections from brands and retailers at a discount, giving new life to excess and overstock product.",
    goodToKnow: "Launched October 2023.",
  },
  {
    id: "circ",
    name: "Circ",
    category: "circularity",
    subcategory: "Circular Materials Innovation",
    borough: "NYC Presence",
    verified: false,
    description: "Textile-to-textile recycling technology that separates poly-cotton blend waste into two new materials, Circ Lyocell and Circ Polyester.",
    goodToKnow: "NYC-based designer Mara Hoffman launched a dress made with Circ Lyocell in New York in October 2023; Circ was also showcased at New York Fashion Week in Christian Siriano's Spring/Summer 2025 collection. Headquartered in Danville, VA.",
  },
  {
    id: "ambercycle",
    name: "Ambercycle",
    category: "circularity",
    subcategory: "Circular Materials Innovation",
    borough: "NYC Presence",
    verified: false,
    description: "Biotechnology company regenerating end-of-life textiles into cycora®, a recycled polyester fiber, to decarbonize fashion and reduce raw material extraction.",
    goodToKnow: "Brooklyn-based designer Kozaburo Akasaka showcased a cycora® capsule collection at New York Fashion Week; also supplies GANNI and Reformation, both with NYC retail presence. Headquartered in Los Angeles, CA.",
  },
  {
    id: "evrnu",
    name: "Evrnu",
    category: "circularity",
    subcategory: "Circular Materials Innovation",
    borough: "NYC Presence",
    verified: false,
    description: "Textile technology company producing NuCycl, a regenerated fiber made from cotton textile waste.",
    goodToKnow: "Launched its first direct-to-consumer product, the 360 Hoodie, in collaboration with Brooklyn-born, FIT-trained designer Christopher Bevans. Headquartered in Seattle, WA.",
  },
  {
    id: "ministry-of-supply",
    name: "Ministry of Supply",
    category: "retail",
    subcategory: "Sustainable Apparel Brand",
    borough: "Manhattan",
    verified: false,
    description: "Performance-driven apparel brand known for tech-forward garments, including a heat-shaped 4D dress made with a wood-pulp-derived viscose \"active yarn.\"",
    goodToKnow: "Formerly ran a SoHo flagship at 138 Wooster St (now closed) and a Lexington Ave pop-up; continues to run 260 Sample Sale events at 261 Fifth Ave, and collaborated with Ponto Footwear on a Mirum plant-based-leather shoe. Headquartered in Boston, MA.",
  },
  {
    id: "natural-fiber-welding",
    name: "Natural Fiber Welding",
    category: "circularity",
    subcategory: "Circular Materials Innovation",
    borough: "NYC Presence",
    verified: false,
    description: "Materials science company producing Mirum, a plastic-free, plant-based leather alternative made without petroleum binders or backers.",
    goodToKnow: "Mirum was used in a Ministry of Supply x Ponto Footwear shoe collaboration; also supplies Allbirds and Patagonia, both with NYC retail presence. Headquartered in Peoria, IL.",
  },
];
